# Generated by Django 3.0.6 on 2020-05-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='orders.PizzaName')),
                ('p_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tops', to='orders.PizzaType')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sz', to='orders.Size')),
            ],
        ),
    ]
