# Generated by Django 3.0.6 on 2020-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200508_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='qty',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.CharField(max_length=256),
        ),
    ]
