# Generated by Django 3.0.6 on 2020-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_id',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
