# Generated by Django 3.0.6 on 2020-05-09 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_auto_20200508_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatter',
            name='user_order',
            field=models.ManyToManyField(blank=True, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
