# Generated by Django 3.0.6 on 2020-05-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_dinnerplatter_user_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatter',
            old_name='user_order',
            new_name='user',
        ),
    ]
