# Generated by Django 3.0.6 on 2020-05-09 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_auto_20200509_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='pasta_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pizza',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='pizza_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salad',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='salad_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sub',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='suborders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='plat_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
