# Generated by Django 3.0.6 on 2020-05-09 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_auto_20200509_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sub',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='sub_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
