# Generated by Django 3.0.6 on 2020-05-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200509_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addition', models.CharField(max_length=64)),
            ],
        ),
    ]
