# Generated by Django 3.0.6 on 2020-05-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200509_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
