# Generated by Django 3.0.6 on 2020-05-09 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0014_addition_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='addn_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sub',
            name='addn',
            field=models.ManyToManyField(blank=True, related_name='subs', to='orders.Addition'),
        ),
    ]
