# Generated by Django 3.0.6 on 2020-05-09 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0015_auto_20200509_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additions',
            field=models.ManyToManyField(blank=True, related_name='addnitems', to='orders.Addition'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='topitems', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='topping',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='topping_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
