# Generated by Django 3.0.6 on 2020-05-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200509_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='additions',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='toppings',
        ),
    ]
